groups:
  - name: api_alerts
    interval: 30s
    rules:
      # API is down
      - alert: APIDown
        expr: up{job=~".*-api"} == 0
        for: 2m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "API {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 2 minutes"
      
      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate is {{ $value | humanizePercentage }} on {{ $labels.job }}"
      
      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High response time on {{ $labels.job }}"
          description: "P95 response time is {{ $value }}s on {{ $labels.job }}"
      
      # High request rate
      - alert: HighRequestRate
        expr: rate(http_requests_total[5m]) > 100
        for: 10m
        labels:
          severity: info
          team: backend
        annotations:
          summary: "High request rate on {{ $labels.job }}"
          description: "Request rate is {{ $value }} req/s on {{ $labels.job }}"

  - name: database_alerts
    interval: 30s
    rules:
      # Database is down
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          team: infra
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute"
      
      # High connection usage
      - alert: HighDatabaseConnections
        expr: (pg_stat_activity_count / pg_settings_max_connections) > 0.8
        for: 5m
        labels:
          severity: warning
          team: infra
        annotations:
          summary: "High database connection usage"
          description: "Database connection usage is {{ $value | humanizePercentage }}"
      
      # Slow queries
      - alert: SlowQueries
        expr: rate(pg_stat_activity_max_tx_duration[5m]) > 30
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Slow database queries detected"
          description: "Queries taking more than 30s detected"
      
      # Database disk usage
      - alert: HighDiskUsage
        expr: (node_filesystem_avail_bytes{mountpoint="/var/lib/postgresql/data"} / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: critical
          team: infra
        annotations:
          summary: "Database disk usage critical"
          description: "Only {{ $value | humanizePercentage }} disk space left"

  - name: celery_alerts
    interval: 60s
    rules:
      # Celery worker down
      - alert: CeleryWorkerDown
        expr: celery_worker_up == 0
        for: 3m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Celery worker is down"
          description: "Celery worker {{ $labels.worker }} has been down for 3 minutes"
      
      # High task failure rate
      - alert: HighTaskFailureRate
        expr: rate(celery_task_failed_total[10m]) > 0.1
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High Celery task failure rate"
          description: "Task failure rate is {{ $value | humanizePercentage }}"
      
      # Task queue backlog
      - alert: TaskQueueBacklog
        expr: celery_queue_length > 1000
        for: 15m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High task queue backlog"
          description: "Queue {{ $labels.queue }} has {{ $value }} pending tasks"

  - name: sync_alerts
    interval: 60s
    rules:
      # High sync conflict rate
      - alert: HighSyncConflicts
        expr: rate(sync_operations_total{status="conflict"}[1h]) > 0.05
        for: 30m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High sync conflict rate"
          description: "Sync conflict rate is {{ $value | humanizePercentage }} in the last hour"
      
      # Sync processing time high
      - alert: SlowSyncProcessing
        expr: histogram_quantile(0.95, rate(sync_processing_duration_seconds_bucket[10m])) > 5
        for: 15m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Slow sync processing"
          description: "P95 sync processing time is {{ $value }}s"

  - name: system_alerts
    interval: 30s
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 10m
        labels:
          severity: warning
          team: infra
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"
      
      # High memory usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.9
        for: 5m
        labels:
          severity: critical
          team: infra
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
      
      # Disk space low
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.15
        for: 10m
        labels:
          severity: warning
          team: infra
        annotations:
          summary: "Low disk space"
          description: "Only {{ $value | humanizePercentage }} disk space left on {{ $labels.mountpoint }}"
